services:
  - type: web
    name: marapolsamovies
    env: python
    build:
      command: pip install -r requirements.txt
    start:
      command: gunicorn marapolsa_movies.wsgi:application
    static:
      - type: static
        name: static
        path: /static
        root: /marapolsa_movies/static
      - type: static
        name: media
        path: /media
        root: /marapolsa_movies/media